model_type: "gpt"
exp_path: "gpt_training"
sample_similar_len: false
num_epochs: 1
batch_size: 4
max_seq_len: 1024
num_workers: 4
persistent_workers: true
use_pin_memory: true
prefetch_factor: 2
lr_scheduler_type: "cosine"
init_lr: 0.001
warmup_epochs: 0
label_smoothing: 0.1
device: "cuda:0"
use_wandb: true
resume_wandb_id: null
track_gradients: false
fp16_training: true
use_grad_accum: true
iters_to_accumulate: 4
dataset_name: "roneneldan/TinyStories"