# .pre-commit-config.yaml

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        language_version: python3
        files: \.py$
        exclude: ^tests/
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3
        additional_dependencies: []

files: \.py$
exclude: ^tests/  # Exclude the tests directory if desired